name: Build Windows Docker Image and Push to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Windows Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mc-trade-sizing:latest .

      - name: Push Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mc-trade-sizing:latest
